# Generated by Django 5.0.2 on 2024-03-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
